# generated by cabal-rpm-2.0.12
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

# requires network
%bcond_with tests

Name:           fedora-composes
Version:        0.1
Release:        1%{?dist}
Summary:        Query Fedora composes

License:        BSD
Url:            https://hackage.haskell.org/package/%{name}
# Begin cabal-rpm sources:
Source0:        https://hackage.haskell.org/package/%{name}-%{version}/%{name}-%{version}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-base-static
BuildRequires:  ghc-bytestring-static
BuildRequires:  ghc-extra-static
BuildRequires:  ghc-http-conduit-static
BuildRequires:  ghc-http-directory-static
BuildRequires:  ghc-simple-cmd-args-static
BuildRequires:  ghc-text-static
BuildRequires:  ghc-time-static
%if %{with tests}
BuildRequires:  ghc-simple-cmd-devel
%endif
# End cabal-rpm deps

%description
CLI tool to list and check status of Fedora composes.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%ghc_bin_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_bin_install
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm install


%check
%if %{with tests}
%cabal_test
%endif


%files
# Begin cabal-rpm files:
%license LICENSE
%doc ChangeLog.md README.md
%{_bindir}/%{name}
%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm files


%changelog
* Fri Aug 12 2022 Jens Petersen <petersen@redhat.com> - 0.1-1
- spec file generated by cabal-rpm-2.0.12
